# Recipe for training an SFT model on an 4xA100 GPU

# Dataset
dataset_name: "dataset/hf_main_1mv_train"
split: "train"
system_prompt: "You are a helpful AI Assistant."
task_prompt: "Format your answer with a single <value>, where <value> is:\n- A **single room name** (e.g., 'Kitchen') for location answers.\n- A **number** (e.g., '3') for counting answers.\n- A **single person name** (e.g., 'Michael') for people answers or 'Nobody' if no person satisfies given conditions."
# Base Model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
tokenizer_name: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
max_seq_length: 2048
vllm_enable_prefix_caching: true
# Peft Model
lora_r: 32
lora_target_modules: "all-linear"
lora_modules_to_save: null
lora_alpha: 32
lora_dropout: 0.05
random_state: 42
use_peft: true
use_liger: true
use_liger_kernel: true
use_sft: true

# Training Args
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
gradient_accumulation_steps: 1
use_gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
dataloader_prefetch_factor: 6
dataloader_num_workers: 16
dataloader_pin_memory: true
group_by_length: true
learning_rate: 3.e-4
lora_learning_rate: 3.e-4
weight_decay: 1.e-4
adam_beta1: 0.9
adam_beta2: 0.999
warmup_ratio: 0.05
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
optim: "adamw_torch"
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
bf16: true
fp16: false
max_steps: -1
num_train_epochs: 5
eval_strategy: epoch
max_grad_norm: 1.0
output_dir: "checkpoints/mv1_sft_qwen_3b_lora"
run_name: "mv1_sft_qwen_3b_lora"
overwrite_output_dir: true
report_to:
  - "wandb"
seed: 42
save_strategy: epoch
# save_steps: -1
save_total_limit: 1
# hub_model_id: "dondo_sss/mmlong-grpo"
# push_to_hub: true