# Recipe for training an SFT model on an 4xA100 GPU

# Dataset
dataset_name: "dataset/hf_main_1mv_train"
split: "train"
system_prompt: "You are a helpful AI Assistant."
task_prompt: |
  Format your final answer with a {"answer": <value>}, where <value> is:
    - A **single room name** (e.g., 'Kitchen') for location answers.
    - A **number** (e.g., '3') for counting answers.
    - A **single person name** (e.g., 'Michael') for people answers or 'Nobody' if no person satisfies given conditions.
# Base Model
r1_format: false
model_name_or_path: tiiuae/Falcon3-Mamba-7B-Instruct
tokenizer_name: tiiuae/Falcon3-Mamba-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: null
max_seq_length: 2048
vllm_enable_prefix_caching: true
# Peft Model
lora_r: 32
lora_target_modules: # "all-linear"
- "x_proj"
- "in_proj"
- "out_proj"
lora_modules_to_save: 
#  - "lm_head"
#  - "embed_tokens"
lora_alpha: 32
lora_dropout: 0.05
random_state: 42
use_peft: true
use_liger: false
use_liger_kernel: true
use_sft: true

# Training Args
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
use_gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
dataloader_prefetch_factor: 6
dataloader_num_workers: 16
dataloader_pin_memory: true
group_by_length: true
learning_rate: 3.e-5
weight_decay: 0.
adam_beta1: 0.9
adam_beta2: 0.99
warmup_ratio: 0.05
lr_scheduler_type: constant_with_warmup
optim: "schedule_free_adamw"
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
bf16: true
fp16: false
max_steps: -1
num_train_epochs: 5
eval_strategy: 'no'
do_eval: false
per_device_eval_batch_size: 8
bf16_full_eval: true
batch_eval_metrics: true
max_grad_norm: 0.5
output_dir: "checkpoints/mv1_sft_mamba_7b_lora"
run_name: "mv1_sft_mamba_7b_lora"
overwrite_output_dir: true
report_to:
  - "wandb"
seed: 42
save_strategy: epoch
# save_steps: -1
save_total_limit: 5
# hub_model_id: "dondo_sss/mmlong-grpo"
# push_to_hub: true